/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerListUi.java
 *
 * Created on Dec 3, 2011, 4:54:01 PM
 */
package org.biz.invoicesystem.master.ui;

import javax.swing.JPanel;
import org.components.windows.TabPanelUI;

/**
 *
 * @author Administrator
 */
public class ItemListUi extends TabPanelUI   {

    /** Creates new form CustomerListUi */
    public ItemListUi() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cItmcode = new org.components.controls.CTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemList = new org.components.controls.CxTable();
        cNewBtn = new org.components.controls.CButton();
        cButton3 = new org.components.controls.CButton();
        cDeleteItem = new org.components.controls.CButton();
        cButton6 = new org.components.controls.CButton();
        cNewBtn1 = new org.components.controls.CButton();

        setLayout(null);

        jLabel1.setText("Item Description Search");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 130, 20);

        cItmcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cItmcodeActionPerformed(evt);
            }
        });
        add(cItmcode);
        cItmcode.setBounds(160, 10, 470, 25);

        tblItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Telephone", "Mobile", "Due (Rs)", "Selection"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemList);
        tblItemList.getColumnModel().getColumn(1).setMinWidth(150);
        tblItemList.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblItemList.getColumnModel().getColumn(1).setMaxWidth(150);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 47, 760, 278);

        cNewBtn.setText("Update");
        cNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNewBtnActionPerformed(evt);
            }
        });
        add(cNewBtn);
        cNewBtn.setBounds(230, 340, 121, 49);

        cButton3.setText("Refresh");
        cButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton3ActionPerformed(evt);
            }
        });
        add(cButton3);
        cButton3.setBounds(490, 340, 121, 49);

        cDeleteItem.setText("Delete");
        cDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeleteItemActionPerformed(evt);
            }
        });
        add(cDeleteItem);
        cDeleteItem.setBounds(360, 340, 121, 49);

        cButton6.setText("Close");
        cButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton6ActionPerformed(evt);
            }
        });
        add(cButton6);
        cButton6.setBounds(620, 340, 110, 50);

        cNewBtn1.setText("New ");
        cNewBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNewBtn1ActionPerformed(evt);
            }
        });
        add(cNewBtn1);
        cNewBtn1.setBounds(100, 340, 121, 49);
    }// </editor-fold>//GEN-END:initComponents

    private void cNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNewBtnActionPerformed

    private void cButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cButton3ActionPerformed

    private void cDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeleteItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDeleteItemActionPerformed

    private void cButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cButton6ActionPerformed

    private void cItmcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cItmcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cItmcodeActionPerformed

    private void cNewBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNewBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNewBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.components.controls.CButton cButton3;
    private org.components.controls.CButton cButton6;
    private org.components.controls.CButton cDeleteItem;
    private org.components.controls.CTextField cItmcode;
    private org.components.controls.CButton cNewBtn;
    private org.components.controls.CButton cNewBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.components.controls.CxTable tblItemList;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabName() {
       return "Customer List";
    }

    @Override
    public JPanel getJPanel() {
    
        return this;    
    }
}
