/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cust.java
 *
 * Created on Nov 18, 2011, 11:54:02 PM
 */
package org.biz.invoicesystem.master.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import org.biz.invoicesystem.entity.master.Customer;
import org.biz.invoicesystem.service.master.CustomerService;
import org.components.windows.TabPanelUI;

/**
 *
 * @author Administrator
 */
public class StaffMasterUI extends TabPanelUI  {

    
     private CustomerService cService;
  
  List<Customer> customers;
  
  Customer customer;

    @Override
    public void init() {
  
        try {
           
   cService=new CustomerService();
   customers=new ArrayList<Customer>();
   customer=new Customer();
   
   
        } catch (Exception e) {
        e.printStackTrace();
        }
        
    }
    /** Creates new form cust */
    public StaffMasterUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cLabel6 = new org.components.controls.CLabel();
        cLabel7 = new org.components.controls.CLabel();
        cLabel2 = new org.components.controls.CLabel();
        cLabel8 = new org.components.controls.CLabel();
        cLabel4 = new org.components.controls.CLabel();
        cTextField2 = new org.components.controls.CTextField();
        cDatePicker1 = new org.components.controls.CDatePicker();
        cLabel5 = new org.components.controls.CLabel();
        cButton1 = new org.components.controls.CButton();
        cButton3 = new org.components.controls.CButton();
        cButton4 = new org.components.controls.CButton();
        cButton5 = new org.components.controls.CButton();
        cTextField3 = new org.components.controls.CTextField();
        cTextField4 = new org.components.controls.CTextField();
        cTextField5 = new org.components.controls.CTextField();
        cTextField6 = new org.components.controls.CTextField();
        cLabel9 = new org.components.controls.CLabel();
        cTextField7 = new org.components.controls.CTextField();
        cLabel10 = new org.components.controls.CLabel();
        cTextField8 = new org.components.controls.CTextField();
        cLabel12 = new org.components.controls.CLabel();
        cTextField10 = new org.components.controls.CTextField();
        cComboBox4 = new org.components.controls.CComboBox();
        cDatePicker2 = new org.components.controls.CDatePicker();
        cLabel16 = new org.components.controls.CLabel();
        cLabel17 = new org.components.controls.CLabel();
        cComboBox5 = new org.components.controls.CComboBox();
        cLabel13 = new org.components.controls.CLabel();
        cComboBox6 = new org.components.controls.CComboBox();
        cLabel14 = new org.components.controls.CLabel();
        cComboBox7 = new org.components.controls.CComboBox();
        cPanel1 = new org.components.containers.CPanel();
        cLabel11 = new org.components.controls.CLabel();
        cTextField9 = new org.components.controls.CTextField();
        cLabel15 = new org.components.controls.CLabel();
        cLabel18 = new org.components.controls.CLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setLayout(null);

        cLabel6.setText("Address");
        add(cLabel6);
        cLabel6.setBounds(390, 100, 63, 25);

        cLabel7.setText("City");
        add(cLabel7);
        cLabel7.setBounds(390, 180, 31, 25);

        cLabel2.setText("Staff Id");
        add(cLabel2);
        cLabel2.setBounds(10, 10, 70, 25);

        cLabel8.setText("Phone");
        add(cLabel8);
        cLabel8.setBounds(390, 220, 48, 25);

        cLabel4.setText("Custmer Name ");
        add(cLabel4);
        cLabel4.setBounds(130, 10, 119, 25);

        cTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField2ActionPerformed(evt);
            }
        });
        add(cTextField2);
        cTextField2.setBounds(90, 50, 250, 25);
        add(cDatePicker1);
        cDatePicker1.setBounds(610, 50, 130, 22);

        cLabel5.setText("Work Started");
        add(cLabel5);
        cLabel5.setBounds(610, 10, 130, 25);

        cButton1.setText("Close");
        add(cButton1);
        cButton1.setBounds(600, 340, 60, 30);

        cButton3.setText("Save");
        cButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton3ActionPerformed(evt);
            }
        });
        add(cButton3);
        cButton3.setBounds(420, 340, 60, 30);

        cButton4.setText("Clear");
        add(cButton4);
        cButton4.setBounds(480, 340, 60, 30);

        cButton5.setText("Delete");
        add(cButton5);
        cButton5.setBounds(540, 340, 60, 30);

        cTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField3ActionPerformed(evt);
            }
        });
        add(cTextField3);
        cTextField3.setBounds(460, 100, 280, 25);

        cTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField4ActionPerformed(evt);
            }
        });
        add(cTextField4);
        cTextField4.setBounds(460, 130, 280, 25);

        cTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField5ActionPerformed(evt);
            }
        });
        add(cTextField5);
        cTextField5.setBounds(460, 180, 280, 25);

        cTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField6ActionPerformed(evt);
            }
        });
        add(cTextField6);
        cTextField6.setBounds(460, 220, 280, 25);

        cLabel9.setText("Mobile");
        add(cLabel9);
        cLabel9.setBounds(390, 260, 48, 25);

        cTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField7ActionPerformed(evt);
            }
        });
        add(cTextField7);
        cTextField7.setBounds(460, 260, 280, 25);

        cLabel10.setText("Email");
        add(cLabel10);
        cLabel10.setBounds(390, 300, 48, 25);

        cTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField8ActionPerformed(evt);
            }
        });
        add(cTextField8);
        cTextField8.setBounds(460, 300, 280, 25);

        cLabel12.setText("Religion");
        add(cLabel12);
        cLabel12.setBounds(10, 170, 70, 25);

        cTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField10ActionPerformed(evt);
            }
        });
        add(cTextField10);
        cTextField10.setBounds(10, 50, 70, 25);

        cComboBox4.setEditable(true);
        add(cComboBox4);
        cComboBox4.setBounds(110, 170, 240, 23);
        add(cDatePicker2);
        cDatePicker2.setBounds(460, 50, 120, 22);

        cLabel16.setText("DOB");
        add(cLabel16);
        cLabel16.setBounds(460, 10, 100, 25);

        cLabel17.setText("Security Role");
        add(cLabel17);
        cLabel17.setBounds(10, 210, 100, 25);

        cComboBox5.setEditable(true);
        add(cComboBox5);
        cComboBox5.setBounds(110, 210, 240, 23);

        cLabel13.setText("Gender");
        add(cLabel13);
        cLabel13.setBounds(10, 90, 70, 25);

        cComboBox6.setEditable(true);
        add(cComboBox6);
        cComboBox6.setBounds(110, 90, 110, 23);

        cLabel14.setText("Initial");
        add(cLabel14);
        cLabel14.setBounds(10, 130, 70, 25);

        cComboBox7.setEditable(true);
        add(cComboBox7);
        cComboBox7.setBounds(110, 130, 110, 23);

        cPanel1.setBackground(new java.awt.Color(255, 255, 255));
        cPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cPanel1.setLayout(null);

        cLabel11.setText("Retype Password");
        cPanel1.add(cLabel11);
        cLabel11.setBounds(10, 90, 130, 25);

        cTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextField9ActionPerformed(evt);
            }
        });
        cPanel1.add(cTextField9);
        cTextField9.setBounds(160, 10, 160, 25);

        cLabel15.setText("Password");
        cPanel1.add(cLabel15);
        cLabel15.setBounds(10, 50, 70, 25);

        cLabel18.setText("Username");
        cPanel1.add(cLabel18);
        cLabel18.setBounds(10, 10, 90, 25);

        jPasswordField1.setText("jPasswordField1");
        cPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(160, 80, 160, 30);

        jPasswordField2.setText("jPasswordField1");
        cPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(160, 40, 160, 30);

        add(cPanel1);
        cPanel1.setBounds(10, 250, 340, 120);
    }// </editor-fold>//GEN-END:initComponents

    private void cTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cTextField2ActionPerformed

    private void cButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton3ActionPerformed
        
        //        if (selectedItem != null) {
        //            Item item = itemService.getDao().deatach(selectedItem, selectedItem.getId());
        //            uiToEty(item);
        //            //            item.setProduct(selectedProd);
        //            itemService.getDao().update(item);
        //            items = itemService.getDao().getAll();
        //            addToTable(items);
        //            return;
        //        }
        
        //        uiToEty(item)?;
        //        item.setProduct(selectedProd);
        
        //        Object [] ss= new Object[]{new Item(),new Customer()};
        //        ipu.populateTable(items);
    }//GEN-LAST:event_cButton3ActionPerformed

    private void cTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField3ActionPerformed

    private void cTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField4ActionPerformed

    private void cTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField5ActionPerformed

    private void cTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField6ActionPerformed

    private void cTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField7ActionPerformed

    private void cTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField8ActionPerformed

    private void cTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField10ActionPerformed

    private void cTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextField9ActionPerformed

    
      /**
     * @param cService the cService to set
     */
    public void setcService(CustomerService cService) {
        this.cService = cService;
    }

    @Override
    public String getTabName() {
        return "Customer Form";
    }

    @Override
    public JPanel getJPanel() {
    
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.components.controls.CButton cButton1;
    private org.components.controls.CButton cButton3;
    private org.components.controls.CButton cButton4;
    private org.components.controls.CButton cButton5;
    private org.components.controls.CComboBox cComboBox4;
    private org.components.controls.CComboBox cComboBox5;
    private org.components.controls.CComboBox cComboBox6;
    private org.components.controls.CComboBox cComboBox7;
    private org.components.controls.CDatePicker cDatePicker1;
    private org.components.controls.CDatePicker cDatePicker2;
    private org.components.controls.CLabel cLabel10;
    private org.components.controls.CLabel cLabel11;
    private org.components.controls.CLabel cLabel12;
    private org.components.controls.CLabel cLabel13;
    private org.components.controls.CLabel cLabel14;
    private org.components.controls.CLabel cLabel15;
    private org.components.controls.CLabel cLabel16;
    private org.components.controls.CLabel cLabel17;
    private org.components.controls.CLabel cLabel18;
    private org.components.controls.CLabel cLabel2;
    private org.components.controls.CLabel cLabel4;
    private org.components.controls.CLabel cLabel5;
    private org.components.controls.CLabel cLabel6;
    private org.components.controls.CLabel cLabel7;
    private org.components.controls.CLabel cLabel8;
    private org.components.controls.CLabel cLabel9;
    private org.components.containers.CPanel cPanel1;
    private org.components.controls.CTextField cTextField10;
    private org.components.controls.CTextField cTextField2;
    private org.components.controls.CTextField cTextField3;
    private org.components.controls.CTextField cTextField4;
    private org.components.controls.CTextField cTextField5;
    private org.components.controls.CTextField cTextField6;
    private org.components.controls.CTextField cTextField7;
    private org.components.controls.CTextField cTextField8;
    private org.components.controls.CTextField cTextField9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
